//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaizesStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contac_mails
    {
        public int id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string emails { get; set; }
        public string title { get; set; }
        public string body { get; set; }
    }
}
