//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaizesStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RaizesEntities : DbContext
    {
        public RaizesEntities()
            : base("name=RaizesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blog> Blog { get; set; }
        public virtual DbSet<Contac_mails> Contac_mails { get; set; }
        public virtual DbSet<Landpage> Landpage { get; set; }
        public virtual DbSet<Layout> Layout { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Stores> Stores { get; set; }
    }
}
